### ISSUE TITLE
Specify a license

### ISSUE THREAD

**Issue by jtwb** [rodriguezcommaj/salted#8]
If someone acquired Litmus today they would also acquire the opportunity to claim infringement against your users.

MIT License would be appropriate. Just a mention in the README would do.

http://choosealicense.com/

**Comment by aarongray** [comment]
+1 Definitely needs a license. Please add one.

**Comment by aarongray** [comment]
Okay, Jason gave the go-ahead to use an MIT license. This issue should be resolved by https://github.com/rodriguezcommaj/salted/pull/12.

**Comment by forsbergplustwo** [comment]
Awesome, thanks very much!

**Comment by jtwb** [comment]
Thanks!
